### ISSUE TITLE
Configuration options

### ISSUE THREAD

**Issue by pmpbar** [commodityvectors/d3-timeline#10]
Are there any configuration options for changing the color of the bars or the background, etc.?

**Comment by grillorafael** [comment]
You can change through css fill property. But it might be useful to either add custom class option or custom color option to a given point/interval

**Comment by pmpbar** [comment]
Thank you! How do I classify or identify the bars? Are they all going to be the same color?

**Comment by grillorafael** [comment]
@pmpbar yes. I'm sure that this is a needed functionality.

As https://github.com/commodityvectors/d3-timeline/issues/3 implies, something will be done. I can try to do it tomorrow but feel free to join the issue with ideas of best ways to, as a developer, be able to apply different styles to different elements.

**Comment by pmpbar** [comment]
I will look into it! Thank you for the quick responses.
