### ISSUE TITLE
IE 11 Symbol is undefined

### ISSUE THREAD

**Issue by cm0n** [commodityvectors/d3-timeline#19]
Hi everyone,

I would like to use the Timeline below IE11. Unfortunately, I get the error message, the symbol is not defended. (On the MS side is also the "symbol" function is not supported in IE11)

Is there work around here for a simple solution to this situation?

**Comment by grillorafael** [comment]
Hi @cm0n 

You can try to use some Symbol Polyfill. Here are some options.

https://github.com/medikoo/es6-symbol
https://babeljs.io/docs/usage/polyfill/
https://github.com/zloirock/core-js#ecmascript-6-symbols

**Comment by cm0n** [comment]
Thank you for your quick response.
I use https://github.com/zloirock/core-js#ecmascript-6-symbols and solved the problem.
