### ISSUE TITLE
Any way to set an arbitrary view begin and end date?

### ISSUE THREAD

**Issue by cretace** [commodityvectors/d3-timeline#31]
I want to set the  chart display to start one week back from now and finish one month ahead from now - and then zoom and scroll will show me any outside events - but the JS takes the range from the overall event dates.
Any ideas?

**Comment by maxnelson** [comment]
The starting zoom level is set by the minDt and maxDt variables, which are declared on line 11 & 12 of the timeline-chart.js file. Simply change these two lines:
```
let minDt = d3.min(allElements, this.getPointMinDt);
let maxDt = d3.max(allElements, this.getPointMaxDt);
```
to the following: 
```
let minDt = new Date().setDate(new Date().getDate() - 7);
let maxDt = new Date().setDate(new Date().getDate() + 31);
```
Hope this helps,

**Comment by grillorafael** [comment]
I believe @maxnelson is correct. 

Just FYI: This library is a bit old and needs a good rewrite using newer d3 library so I'm welcoming PRs on that direction

**Comment by grillorafael** [comment]
I'll close the issue for now. Please reopen if necessary.

**Comment by cretace** [comment]
Just need to say a massive thanks to Max Nelson ! Perfect - I'd tried setting that but got it wrong.
This is the best timeline of the several similar ones around so great to keep it going.
(There's some oddities with custom class as it seems incomplete but not hard to adapt)
