### ISSUE TITLE
self.onVizChange.call is not a function

### ISSUE THREAD

**Issue by aderito7** [commodityvectors/d3-timeline#6]
Using the example from the README.MD, the chart seems to draw well onto the screen, but scrolling on it returns the titled error.

**Comment by grillorafael** [comment]
Hi! Thanks for your feedback. I'll check this issue and fix it in a couple
of minutes

**Comment by grillorafael** [comment]
Hey @aderito7 can you check if fa92abb13c8a69bdc6c88123155851321f32b8d2 fix your issue?

I already bumped to 1.0.2 on NPM as well

**Comment by aderito7** [comment]
That seems to have done the trick.
Thank you
