### ISSUE TITLE
Labels overlapping title

### ISSUE THREAD

**Issue by aderito7** [commodityvectors/d3-timeline#7]
![image](https://cloud.githubusercontent.com/assets/16321230/13345754/ffae9dc2-dc69-11e5-9b8d-f445ea93f063.png)
I see the labels here are overlapping the titles fixed on the left-hand side It's apparently not so with the demo

**Comment by grillorafael** [comment]
Hi @aderito7 can you provide us a codepen with the issue? 

Did you import the stylesheet as well?

**Comment by aderito7** [comment]
There is one stylesheet under dist 
```html
<link href="node_modules/d3-timeline-chart/dist/timeline-chart.css" rel="stylesheet">
```
and I have this included

**Comment by grillorafael** [comment]
So can you provide a jsfiddle or a codepen with the issue?

**Comment by aderito7** [comment]
I just can't find a CDN for this project, however I can give you that I use this....
```typescript
var schedules = [[{"employee":"Batman","client":"Lex Luthor","project":"Save Earth","schedule":{"from":"2016-03-10T07:18:05.960Z","to":"2016-08-20T07:18:05.960Z"}}],[{"employee":"Wonder Woman","client":"The Daily Dispatch","project":"Hero Academy","schedule":{"from":"2016-05-11T07:18:05.973Z","to":"2016-07-12T07:18:05.973Z"}}],[{"employee":"Wonder Woman","client":"Wayne Enterprise","project":"Deflect Meteor","schedule":{"from":"2016-04-08T07:18:05.976Z","to":"2016-06-26T07:18:05.976Z"}}],[{"employee":"Wonder Woman","client":"Mars Corp","project":"Make Mars Inhabitable","schedule":{"from":"2016-05-12T07:18:05.976Z","to":"2016-07-13T07:18:05.976Z"}}],[{"employee":"Wonder Woman","client":"Lex Luthor","project":"Save Earth","schedule":{"from":"2016-03-30T07:18:05.977Z","to":"2016-07-06T07:18:05.977Z"}}],[{"employee":"Cat Woman","client":"Mars Corp","project":"Make Mars Inhabitable","schedule":{"from":"2016-03-12T07:18:05.977Z","to":"2016-08-16T07:18:05.977Z"}}],[{"employee":"Cat Woman","client":"Lex Luthor","project":"Save Earth","schedule":{"from":"2016-03-05T07:18:05.977Z","to":"2016-08-02T07:18:05.977Z"}}],[{"employee":"Supergirl","client":"Mars Corp","project":"Make Mars Inhabitable","schedule":{"from":"2016-05-01T07:18:05.978Z","to":"2016-07-09T07:18:05.978Z"}}],[{"employee":"Supergirl","client":"Lex Luthor","project":"Save Earth","schedule":{"from":"2016-04-26T07:18:05.978Z","to":"2016-09-04T07:18:05.978Z"}}]];

let data = [],
            obj = {};
        
        schedules.forEach((schedule) => {
           var key = schedule[0].employee,
               times = schedule[0].schedule;
           if (!obj[key]) {
               obj[key] = {
                   label: key,
                   data: []
               };
           }
           obj[key].data.push({
               type: TimelineChart.TYPE.INTERVAL,
               from: new Date(times.from),
               to: new Date(times.to),
               label: schedule[0].project,
               fill: colorScale
           })
        });
        
        for (var key in obj) {
            data.push({
                label: obj[key].label,
                data: obj[key].data
            });
        }
        let timeline = new TimelineChart(parent[0], data, {
            
        });
```

**Comment by grillorafael** [comment]
So, I tried this here http://codepen.io/grillorafael/pen/Yqzzrz and the issue is not happening. What's happening is that you have multiple elements overlaping each other times and the labels gets mixed.

Check if I managed to replicate your code properly.

**Comment by aderito7** [comment]
The issue is not present on that codepen, however I fail to see what is being done different.

**Comment by grillorafael** [comment]
Is there any other styles being imported? Is scripts running?

**Comment by aderito7** [comment]
I've included this library into a rather large project. I have semantic ui and angular 2 running. I haven't written any stylesheets of my own. I now see that the code itself does in fact work. I will look deeper into it myself and hopefully figure it out

**Comment by grillorafael** [comment]
I see. One thing that might be the issue is that this is being clipped by
an svg clip path, which is relative to the current svg element unless you
are using a meta base then it would look at base#clippathreference.

Can you check if this might be the issue?

**Comment by grillorafael** [comment]
Hi @aderito7. Any news on that?

**Comment by aderito7** [comment]
I will close this. The library works fine, just an issue with my other items I haven't been able to identify which causing the issues. Thanks
