### ISSUE TITLE
Error: Invalid value for <rect> attribute width="NaN"

### ISSUE THREAD

**Issue by aderito7** [commodityvectors/d3-timeline#8]
![image](https://cloud.githubusercontent.com/assets/16321230/13354403/7d0d78f4-dca3-11e5-9864-de37de6cedfe.png)

At some point 'over-zooming' out starts causing these errors to be thrown to the console and it seems the timeline stops working.

**Comment by grillorafael** [comment]
Hey @aderito7. Try to put up a codepen in place. You can use github raw files to import but use like this

https://rawgit.com/commodityvectors/d3-timeline/master/dist/timeline-chart.js

instead of 

https://raw.githubusercontent.com/commodityvectors/d3-timeline/master/dist/timeline-chart.js

**Comment by aderito7** [comment]
I guess this could be another issue of my external libraries interfering here (Angular 2 / Semantic UI), but I can't get the same errors showing again outside my app

**Comment by grillorafael** [comment]
Hi @aderito7. Any news on that?
